version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - "5672:5672"
      - "15672:15672"
  api-gateway:
    container_name: gateway-service
    build:
      context: ../api-gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4000:4000"
    env_file: ../api-gateway/configs/.env
  auth-service:
    container_name: auth-service
    build:
      context: ../auth-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4001:4001"
    env_file: ../auth-service/configs/.env
  company-service:
    container_name: company-service
    build:
      context: ../company-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4004:4004"
    env_file: ../company-service/configs/.env
  profile-service:
    container_name: profile-service
    build:
      context: ../profile-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4003:4003"
    env_file: ../profile-service/configs/.env
    