version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - "5672:5672"
      # Management UI
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping", "--quiet"]
      interval: 10s
      timeout: 30s
      retries: 5
  api-gateway:
    container_name: gateway-service
    build:
      context: ../api-gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4000:4000"
    env_file: ../api-gateway/configs/.env
    volumes:
      - ../api-gateway/src:/app/src
  auth-service:
    container_name: auth-service
    build:
      context: ../auth-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4001:4001"
    env_file: ../auth-service/configs/.env
    depends_on:
      - rabbitmq
    volumes:
      - ../auth-service/src:/app/src
  notification:
    container_name: notification-service
    build:
      context: ../notification
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4002:4002"
    env_file: ../notification/configs/.env
    depends_on:
      - rabbitmq
    volumes:
      - ../notification/src:/app/src
